export const bookings = [
    {
        id: 1,
        date: "2024-11-04T10:00:00",
        status: "Upcoming",
        shopName: "Lighthouse Barbers",
        shopAddress: "Malviya Nagar, Jaipur, Rajasthan",
        services: ["Haircut", "Manicure", "Pedicure"],
        image: require('../assets/images/ShopProfileImage/Salon_1.png'),
    },
    {
        id: 2,
        date: "2024-10-30T15:00:00",
        status: "Completed",
        shopName: "The Hair Studio",
        shopAddress: "C-Scheme, Jaipur, Rajasthan",
        services: ["Shave", "Facial"],
        image: require('../assets/images/ShopProfileImage/Salon_2.png'),
    },
    {
        id: 3,
        date: "2024-10-25T09:00:00",
        status: "Cancelled",
        shopName: "Glamour Salon",
        shopAddress: "Bani Park, Jaipur, Rajasthan",
        services: ["Hair Color"],
        image: require('../assets/images/ShopProfileImage/Salon_3.png'),
    },
    {
        id: 4,
        date: "2024-11-05T12:00:00",
        status: "Upcoming",
        shopName: "Stylish Cuts",
        shopAddress: "Jagatpura, Jaipur, Rajasthan",
        services: ["Haircut", "Beard Trim"],
        image: require('../assets/images/ShopProfileImage/Spa_1.png'),
    },
    {
        id: 5,
        date: "2024-10-28T14:30:00",
        status: "Completed",
        shopName: "Elite Salon",
        shopAddress: "Tonk Road, Jaipur, Rajasthan",
        services: ["Pedicure", "Nail Art"],
        image: require('../assets/images/ShopProfileImage/Spa_2.png'),
    },
    {
        id: 6,
        date: "2024-11-10T11:00:00",
        status: "Upcoming",
        shopName: "Classic Cuts",
        shopAddress: "Ajmer Road, Jaipur, Rajasthan",
        services: ["Haircut", "Coloring"],
        image: require('../assets/images/ShopProfileImage/Spa_3.png'),
    },
    {
        id: 7,
        date: "2024-11-12T16:00:00",
        status: "Upcoming",
        shopName: "Chic Hair Studio",
        shopAddress: "Vidhyadhar Nagar, Jaipur, Rajasthan",
        services: ["Hair Styling", "Facial"],
        image: require('../assets/images/ShopProfileImage/Parlour_1.png'),
    },
    {
        id: 8,
        date: "2024-11-15T09:30:00",
        status: "Completed",
        shopName: "Glamour House",
        shopAddress: "Shastri Nagar, Jaipur, Rajasthan",
        services: ["Nail Art", "Haircut"],
        image: require('../assets/images/ShopProfileImage/Parlour_2.png'),
    },
    {
        id: 9,
        date: "2024-11-20T14:00:00",
        status: "Upcoming",
        shopName: "Modern Looks",
        shopAddress: "Sanganer, Jaipur, Rajasthan",
        services: ["Beard Trim", "Shave"],
        image: require('../assets/images/ShopProfileImage/Parlour_3.png'),
    },
    {
        id: 10,
        date: "2024-11-22T13:00:00",
        status: "Completed",
        shopName: "Trendy Hair Salon",
        shopAddress: "Malviya Nagar, Jaipur, Rajasthan",
        services: ["Hair Color", "Beard Styling"],
        image: require('../assets/images/ShopProfileImage/Salon_1.png'),
    },
];
